Models/Tablero.cs
using tl2_tp10_2023_castroagustin.ViewModels;

namespace tl2_tp10_2023_castroagustin;

public class Tablero
{
    private int id;
    private int idUsuarioPropietario;
    private string nombre;
    private string descripcion;

    public int Id { get => id; set => id = value; }
    public int IdUsuarioPropietario { get => idUsuarioPropietario; set => idUsuarioPropietario = value; }
    public string Nombre { get => nombre; set => nombre = value; }
    public string Descripcion { get => descripcion; set => descripcion = value; }

    public Tablero() { }
    public Tablero(CrearTableroViewModel tablero)
    {
        this.idUsuarioPropietario = tablero.IdUsuarioPropietario;
        this.nombre = tablero.Nombre;
        this.descripcion = tablero.Descripcion;
    }
    public Tablero(ModificarTableroViewModel tablero)
    {
        this.id = tablero.Id;
        this.idUsuarioPropietario = tablero.IdUsuarioPropietario;
        this.nombre = tablero.Nombre;
        this.descripcion = tablero.Descripcion;
    }
}

Controllers/TableroController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using tl2_tp10_2023_castroagustin.Models;
using tl2_tp10_2023_castroagustin.Repositorios;
using tl2_tp10_2023_castroagustin.ViewModels;

namespace tl2_tp10_2023_castroagustin.Controllers;

public class TableroController : Controller
{
    private readonly ITableroRepository _tableroRepository;
    private readonly ITareaRepository _tareaRepository;
    private readonly IUsuarioRepository _usuarioRepository;
    private readonly ILogger<TableroController> _logger;

    public TableroController(ILogger<TableroController> logger, ITableroRepository tableroRepository, ITareaRepository tareaRepository, IUsuarioRepository usuarioRepository)
    {
        _logger = logger;
        _tableroRepository = tableroRepository;
        _tareaRepository = tareaRepository;
        _usuarioRepository = usuarioRepository;
    }

    public IActionResult Index()
    {
        try
        {
            if (!logueado()) return RedirectToRoute(new { controller = "Login", action = "Index" });
            if (esAdmin())
            {
                var tableros = _tableroRepository.GetAll();
                var usuarios = _usuarioRepository.GetAll();
                return View(new ListarTablerosViewModel(tableros, usuarios, (int)HttpContext.Session.GetInt32("id")));
            }
            else
            {
                var tableros = _tableroRepository.GetAllByUser((int)HttpContext.Session.GetInt32("id"));
                return View(new ListarTablerosViewModel(tableros, _tableroRepository.GetAllByAssigned((int)HttpContext.Session.GetInt32("id")), _usuarioRepository.GetAll(), (int)HttpContext.Session.GetInt32("id")));
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    [HttpGet]
    public IActionResult CreateTablero()
    {
        try
        {
            if (!logueado()) return RedirectToRoute(new { controller = "Login", action = "Index" });
            return View(new CrearTableroViewModel { IdUsuarioPropietario = (int)HttpContext.Session.GetInt32("id") });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    [HttpPost]
    public IActionResult CreateTablero(CrearTableroViewModel tablero)
    {
        try
        {
            if (!logueado()) return RedirectToRoute(new { controller = "Login", action = "Index" });
            if (!ModelState.IsValid) return RedirectToAction("CreateTablero");
            _tableroRepository.Create(new Tablero(tablero));
            _logger.LogWarning("nombre tablero {0}", tablero.Nombre);
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    [HttpGet]
    public IActionResult UpdateTablero(int id)
    {
        try
        {
            if (!logueado()) return RedirectToRoute(new { controller = "Login", action = "Index" });
            var tablero = _tableroRepository.Get(id);
            return View(new ModificarTableroViewModel(tablero));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }
    [HttpPost]
    public IActionResult UpdateTablero(ModificarTableroViewModel tablero)
    {
        try
        {
            if (!logueado()) return RedirectToRoute(new { controller = "Login", action = "Index" });
            if (!ModelState.IsValid) return RedirectToAction("Index");
            _tableroRepository.Update(tablero.Id, new Tablero(tablero));
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }


    public IActionResult DeleteTablero(int id)
    {
        try
        {
            if (!logueado()) return RedirectToRoute(new { controller = "Login", action = "Index" });
            if (!esAdmin())
            {
                var tablero = _tableroRepository.Get(id);
                if ((int)HttpContext.Session.GetInt32("id") != tablero.IdUsuarioPropietario) return RedirectToAction("Index");
            }
            var tareas = _tareaRepository.GetAllByTablero(id);
            foreach (var tarea in tareas)
            {
                _tareaRepository.Remove(tarea.Id);
            }
            _tableroRepository.Remove(id);
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    private bool logueado()
    {
        return HttpContext.Session.Keys.Any();
    }

    private bool esAdmin()
    {
        return HttpContext.Session.Keys.Any() && HttpContext.Session.GetString("rol") == Roles.administrador.ToString();
    }
}

Controllers/TareaController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using tl2_tp10_2023_castroagustin.Models;
using tl2_tp10_2023_castroagustin.Repositorios;
using tl2_tp10_2023_castroagustin.ViewModels;

namespace tl2_tp10_2023_castroagustin.Controllers;

public class TareaController : Controller
{
    private readonly ITareaRepository _tareaRepository;
    private readonly ITableroRepository _tableroRepository;
    private readonly IUsuarioRepository _usuarioRepository;
    private TableroRepository tableroRepository;
    private readonly ILogger<TareaController> _logger;

    public TareaController(ILogger<TareaController> logger, ITareaRepository tareaRepository, ITableroRepository tableroRepository, IUsuarioRepository usuarioRepository)
    {
        _logger = logger;
        _tareaRepository = tareaRepository;
        _tableroRepository = tableroRepository;
        _usuarioRepository = usuarioRepository;
    }

    public IActionResult Index(int id)
    {
        try
        {
            if (!logueado()) return RedirectToRoute(new { controller = "Login", action = "Index" });

            if (!esAdmin())
            {
                int idUser = (int)HttpContext.Session.GetInt32("id");
                var tableros = _tableroRepository.GetAllByUser(idUser);
                var tareas = _tareaRepository.GetAllByTablero(id);
                if (tableros.Any(t => t.Id == id) || tareas.Any(t => t.IdUsuarioAsignado == idUser))
                {
                    return View(new ListarTareasViewModel(_tareaRepository.GetAllByTablero(id), _tableroRepository.Get(id), _usuarioRepository.GetAll()));
                }
            }
            else
            {
                return View(new ListarTareasViewModel(_tareaRepository.GetAllByTablero(id), _tableroRepository.Get(id), _usuarioRepository.GetAll()));
            }
            return RedirectToRoute(new { controller = "Tablero", action = "Index" });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    [HttpGet]
    public IActionResult CreateTarea(int id)
    {
        try
        {
            if (!logueado()) return RedirectToRoute(new { controller = "Login", action = "Index" });
            var tablero = _tableroRepository.Get(id);
            return View(new CrearTareaViewModel
            {
                IdTablero = id,
                IdUsuarioPropietario = (int)HttpContext.Session.GetInt32("id"),
                Usuarios = _usuarioRepository.GetAll(),
                NombreTablero = tablero.Nombre
            });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    [HttpPost]
    public IActionResult CreateTarea(CrearTareaViewModel tarea)
    {
        try
        {
            if (!logueado()) return RedirectToRoute(new { controller = "Login", action = "Index" });
            if (!ModelState.IsValid) return RedirectToAction("Index", new { id = tarea.IdTablero });
            _tareaRepository.Create(tarea.IdTablero, new Tarea(tarea));
            return RedirectToAction("Index", new { id = tarea.IdTablero });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    [HttpGet]
    public IActionResult UpdateTarea(int id)
    {
        try
        {
            if (!logueado()) return RedirectToRoute(new { controller = "Login", action = "Index" });
            var tarea = _tareaRepository.Get(id);
            var tablero = _tableroRepository.Get(tarea.IdTablero);

            return View(new ModificarTareaViewModel(tarea, _usuarioRepository.GetAll(), tablero.IdUsuarioPropietario));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    [HttpPost]
    public IActionResult UpdateTarea(ModificarTareaViewModel tarea)
    {
        try
        {
            if (!logueado()) return RedirectToRoute(new { controller = "Login", action = "Index" });
            if (!ModelState.IsValid) return RedirectToAction("Index", new { id = tarea.IdTablero });
            _tareaRepository.Update(tarea.Id, new Tarea(tarea));
            return RedirectToAction("Index", new { id = tarea.IdTablero });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    public IActionResult UpdateEstado(int id)
    {
        try
        {
            if (!logueado()) return RedirectToRoute(new { controller = "Login", action = "Index" });
            var tarea = _tareaRepository.Get(id);
            return View(new ModificarEstadoTareaViewModel(tarea));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }
    [HttpPost]
    public IActionResult UpdateEstado(ModificarEstadoTareaViewModel tarea)
    {
        try
        {
            if (!logueado()) return RedirectToRoute(new { controller = "Login", action = "Index" });
            if (!ModelState.IsValid) return RedirectToAction("Index", new { id = tarea.IdTablero });
            var tareaMod = _tareaRepository.Get(tarea.Id);
            tareaMod.Estado = tarea.Estado;
            _tareaRepository.Update(tarea.Id, tareaMod);
            return RedirectToAction("Index", new { id = tarea.IdTablero });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    public IActionResult DeleteTarea(int id)
    {
        try
        {
            if (!logueado()) return RedirectToRoute(new { controller = "Login", action = "Index" });
            if (!ModelState.IsValid) return RedirectToAction("Index", id);

            var idTablero = _tareaRepository.Get(id).IdTablero;
            _tareaRepository.Remove(id);
            return RedirectToAction("Index", new { id = idTablero });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    private bool logueado()
    {
        return HttpContext.Session.Keys.Any();
    }

    private bool esAdmin()
    {
        return HttpContext.Session.Keys.Any() && HttpContext.Session.GetString("rol") == Roles.administrador.ToString();
    }
}

Views/Tablero/CreateTablero.cshtml
@model tl2_tp10_2023_castroagustin.ViewModels.CrearTableroViewModel


<form asp-controller="Tablero" asp-action="CreateTablero" class="container" style="max-width: 500px">
    <h4>Crear Tablero</h4>
    <div class="form-group">
        <input asp-for="@Model.IdUsuarioPropietario" class="form-control" hidden />
        <span asp-validation-for="@Model.IdUsuarioPropietario" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Nombre"></label>
        <input asp-for="@Model.Nombre" class="form-control" />
        <span asp-validation-for="@Model.Nombre" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Descripcion"></label>
        <input asp-for="@Model.Descripcion" class="form-control" />
        <span asp-validation-for="@Model.Descripcion" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary mt-3">Crear</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/Tablero/DeleteTablero.cshtml
@{
    ViewData["Title"] = "Eliminar Tablero";
}
@model Tablero



<form asp-controller="Tablero" asp-action="DeleteTablero">
    <div class="form-group">
        <label asp-for="@Model.Id">Id tablero a eliminar:</label>
        <input asp-for="@Model.Id" class="form-control" />
    </div>

    <button type="submit" class="btn btn-primary">Eliminar</button>
</form>

Views/Tablero/UpdateTablero.cshtml
@model tl2_tp10_2023_castroagustin.ViewModels.ModificarTableroViewModel


<form asp-controller="Tablero" asp-action="UpdateTablero" class="container" style="max-width: 500px">
    <h4>Modificar tablero "@Model.Nombre"</h4>
    <div class="form-group">
        <input asp-for="@Model.Id" hidden />
        <input asp-for="@Model.IdUsuarioPropietario" hidden />
        <label asp-for="@Model.Nombre"></label>
        <input asp-for="@Model.Nombre" class="form-control" />
        <span asp-validation-for="@Model.Nombre" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Descripcion"></label>
        <input asp-for="@Model.Descripcion" class="form-control" />
        <span asp-validation-for="@Model.Descripcion" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary mt-3">Enviar</button>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/Tablero/index.cshtml
@{
    ViewData["Title"] = "Tableros";
}

@model tl2_tp10_2023_castroagustin.ViewModels.ListarTablerosViewModel

<h2> Lista de Tableros </h2>
<a asp-controller="Tablero" asp-action="CreateTablero" class="btn btn-outline-primary">Crear Tablero</a>

<table class="table table-striped">
    <thead>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>Propietario</th>
        <th></th>
        <th></th>
        <th></th>
    </thead>
    <tbody>
        @foreach (var tablero in Model.Tableros)
        {
            <tr>
                <td>@tablero.Nombre</td>
                <td>@tablero.Descripcion</td>
                <td>@tablero.NombreUsuarioPropietario</td>
                <td>
                    <a asp-controller="Tarea" asp-action="Index" asp-route-id="@tablero.Id"
                        class="btn btn-outline-success">Ver Tareas</a>
                </td>
                @if (@tablero.IdUsuarioPropietario == Context.Session.GetInt32("id") || Context.Session.GetString("rol") ==
               Roles.administrador.ToString())
                {
                    <td><a asp-controller="Tarea" asp-action="CreateTarea" asp-route-id="@tablero.Id"
                            class="btn btn-success">Agregar Tarea</a></td>
                    <td>
                        <a asp-controller="Tablero" asp-action="UpdateTablero" asp-route-id="@tablero.Id"
                            class="btn btn btn-secondary">Modificar</a>
                        <a asp-controller="Tablero" asp-action="DeleteTablero" asp-route-id="@tablero.Id" class="btn btn-danger"
                            onclick="return confirm(`¿Eliminar el tablero '@tablero.Nombre?'`)">Eliminar</a>
                    </td>
                }
                else
                {
                    <td></td>
                    <td></td>
                }
            </tr>
        }
    </tbody>
</table>